name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    # exclude:
    # - feature/*

stages:
  - stage: deployCoreDev
    displayName: Core - DEV
    jobs:
    - template: core-deploy.yml
      parameters:
        serviceConnection: $(devServiceConnection)
        subscriptionId: $(devSubscriptionId)
        environmentName: dev
        environmentId: d01

  - stage: deployCoreDev
    displayName: Core - TEST
    jobs:
    - template: core-deploy.yml
      parameters:
        serviceConnection: $(testServiceConnection)
        subscriptionId: $(testSubscriptionId)
        environmentName: test
        environmentId: t01

  # - stage: deployTestApis
  #   displayName: TestApis - DEV
  #   jobs:
  #   - template: test-api-deploy.yml
  #     parameters:
  #       serviceConnection: $(devServiceConnection)
  #       subscriptionId: $(devSubscriptionId)
  #       environmentName: dev
  #       environmentId: d01
  
  - stage: deployAgDev
    displayName: Gateway - DEV
    dependsOn: 
    - deployCoreDev
    jobs:
    - template: ag-deploy.yml
      parameters:
        serviceConnection: $(devServiceConnection)
        subscriptionId: $(devSubscriptionId)
        environmentName: dev
        environmentId: d01
        globalKeyVaultName: s141d01-signin-global-kv
        sslCertificateName: signin-generic

  - stage: deployAgTest
    displayName: Gateway - TEST
    dependsOn: 
    - deployCoreDev
    jobs:
    - template: ag-deploy.yml
      parameters:
        serviceConnection: $(testServiceConnection)
        subscriptionId: $(testSubscriptionId)
        environmentName: test
        environmentId: t01
        globalKeyVaultName: s141d01-signin-global-kv
        sslCertificateName: signin-generic