parameters:
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: environmentName
  type: string
- name: deploymentLocation
  type: string
  default: 'westeurope'
- name: projectId
  type: string
  default: 's141'
- name: environmentId
  type: string

jobs:
- deployment: deploy
  displayName: deploy core vnet - ${{parameters.environmentName}}
  environment: ${{parameters.environmentName}}
  pool:
    vmImage: ubuntu-latest
  variables:
    overrideParameters: '
    -applicationName "gateway"
    -environmentName "${{parameters.environmentName}}"
    '
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - pwsh: |
            Get-ChildItem -Path $(Pipeline.Workspace) –Recurse
        - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            subscriptionId: ${{parameters.subscriptionId}}
            resourceGroupName: ${{parameters.projectId}}${{parameters.environmentId}}-gateway${{parameters.environmentName}}
            location: ${{parameters.deploymentLocation}}
            templateFilePath: '$(Pipeline.Workspace)/s/login.dfe.gateway/src/arm/gateway.json'
            armParameterOverrideString: $(overrideParameters)
            processOutputs: false