parameters:
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: environmentName
  type: string
- name: applicationName
  type: string
  default: gateway
- name: deploymentLocation
  type: string
  default: 'westeurope'
- name: projectId
  type: string
  default: 's141'
- name: environmentId
  type: string
- name: projectCoreRgSuffix
  type: string  
  default: projectcore 
- name: subnetName
  type: string  
  default: service


jobs:
- deployment: deploy
  displayName: deploy ag - ${{parameters.environmentName}}
  environment: ${{parameters.environmentName}}
  pool:
    vmImage: ubuntu-latest
  variables:
    keyVaultName: ${{parameters.projectId}}-signin-global-kv
    resourceGroupName: ${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.environmentName}}gateway
    gatewayIdentityName: ${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.environmentName}}gateway
    overrideParameters: '
    -applicationName "gateway"
    -environmentName "${{parameters.environmentName}}"
    -projectCoreRgName "${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.projectCoreRgSuffix}}"
    -vnetName "${{parameters.applicationName}}-${{parameters.environmentName}}-vnet"
    -subnetName "${{parameters.subnetName}}"
    '
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self

        - task: AzureCLI@2
          displayName: Pre Deploy
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              write-host creating ident for ag
              $ident = az identity create -g $env:RESOURCEGROUPNAME -n $env:GATEWAYIDENTITYNAME | ConvertFrom-Json
              write-host created identity : $ident.name
              write-host setting kv policy for $ident.name
              az keyvault set-policy --name $env:KEYVAULTNAME --object-id $ident.principalId --certificate-permissions get getissuers list listissuers
              write-host puttin principalId $ident.principalId on the pipeline
              Write-Host "##vso[task.setvariable variable=$principalId]$ident.principalId"

        - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            subscriptionId: ${{parameters.subscriptionId}}
            resourceGroupName: $(resourceGroupName)
            location: ${{parameters.deploymentLocation}}
            templateFilePath: '$(Pipeline.Workspace)/s/login.dfe.gateway/src/arm/gateway.json'
            armParameterOverrideString: $(overrideParameters)
            processOutputs: true

        - task: AzureCLI@2
          displayName: Post Deploy
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              $ident = az identity show -g $env:RESOURCEGROUPNAME -n $env:GATEWAYIDENTITYNAME | ConvertFrom-Json
              az network application-gateway identity assign -g $env:RESOURCEGROUPNAME --gateway-name $env:ARMOUTPUT_RESOURCENAME --identity $ident.id