parameters:
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: environmentName
  type: string
- name: applicationName
  type: string
  default: gateway
- name: deploymentLocation
  type: string
  default: 'westeurope'
- name: projectId
  type: string
  default: 's141'
- name: environmentId
  type: string
- name: projectCoreRgSuffix
  type: string  
  default: projectcore 
- name: subnetName
  type: string  
  default: service


jobs:
- deployment: deploy
  displayName: deploy ag - ${{parameters.environmentName}}
  environment: ${{parameters.environmentName}}
  pool:
    vmImage: ubuntu-latest
  variables:
    resourceGroupName: ${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.environmentName}}gateway
    gatewayIdentityName: ${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.environmentName}}gateway
    overrideParameters: '
    -applicationName "gateway"
    -environmentName "${{parameters.environmentName}}"
    -projectCoreRgName "${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.projectCoreRgSuffix}}"
    -vnetName "${{parameters.applicationName}}-${{parameters.environmentName}}-vnet"
    -subnetName "${{parameters.subnetName}}"
    '
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self

        - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            subscriptionId: ${{parameters.subscriptionId}}
            resourceGroupName: $(resourceGroupName)
            location: ${{parameters.deploymentLocation}}
            templateFilePath: '$(Pipeline.Workspace)/s/login.dfe.gateway/src/arm/gateway.json'
            armParameterOverrideString: $(overrideParameters)
            processOutputs: true

        - task: AzureCLI@2
          displayName: Create and assign AG identity
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo AGNAME : $ARMOUTPUT_RESOURCEID
              echo RG : $RESOURCEGROUPNAME
              echo ID : $GATEWAYIDENTITYNAME
              IDENTITYID=$(az identity create -g $RESOURCEGROUPNAME -n $GATEWAYIDENTITYNAME --query id --output tsv)
              echo created $IDENTITYID