parameters:
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: environmentName
  type: string
- name: applicationName
  type: string
  default: gateway
- name: deploymentLocation
  type: string
  default: 'westeurope'
- name: projectId
  type: string
  default: 's141'
- name: environmentId
  type: string
- name: projectCoreRgSuffix
  type: string
  default: projectcore

jobs:
- deployment: deploy
  displayName: deploy core vnet - ${{parameters.environmentName}}
  environment: ${{parameters.environmentName}}
  pool:
    vmImage: windows-latest
  variables:
  - group: platform-${{parameters.environmentName}}
  - name: overrideParameters
    value: '
    -applicationName "${{parameters.applicationName}}"
    -environmentName "${{parameters.environmentName}}"
    -serviceSubnetPrefix "$(gatewaySubnetPrefix)"
    '
  - name:  serverName
    value: "${{parameters.projectId}}${{parameters.environmentId}}-signin-shd-sql.database.windows.net"
  - name:  databaseName
    value: "${{parameters.projectId}}${{parameters.environmentId}}-signin-organisations-db"
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: SqlAzureDacpacDeployment@1
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            AuthenticationType: 'servicePrincipal'
            ServerName: $serverName
            DatabaseName: $databaseName
            deployType: 'InlineSqlTask'
            SqlInline: |
              declare @results varchar(max)
              
              select @results = coalesce(@results + ',', '') +  [redirectUrl]
              from [dbo].[serviceRedirectUris]
              order by [redirectUrl]
              
              select @results as results
            IpDetectionMethod: 'AutoDetect'
        - task: AzurePowerShell@5
          displayName: SQL Server Redirect urls list
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            ScriptType: 'InlineScript'
            inline: |
              $projectCore = $env:PROJECTCORE
              $sqlServerFQDN = "$projectCore-signin-shd-sql.database.windows.net"

              $databaseName = "$projectCore-signin-organisations-db"

              $userQuery = "
                declare @results varchar(max)

                select @results = coalesce(@results + ',', '') +  [redirectUrl]
                from [dbo].[serviceRedirectUris]
                order by [redirectUrl]

                select @results as results
              "

              $access_token = (Get-AzAccessToken -ResourceUrl https://database.windows.net).Token

              Invoke-Sqlcmd -ServerInstance $sqlServerFQDN -Database $databaseName -AccessToken $access_token -query $userQuery -Verbose
              $results = Invoke-Sqlcmd -ServerInstance $sqlServerFQDN -Database $databaseName -query $userQuery -Verbose
              $results = $results -replace '"',''
              write-host "##vso[task.setvariable variable=redirectUrls]$results"

              write-host $redirectUrls

            azurePowerShellVersion: 'LatestVersion'
            pwsh: true
        # - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
        #   parameters:
        #     serviceConnection: ${{parameters.serviceConnection}}
        #     subscriptionId: ${{parameters.subscriptionId}}
        #     resourceGroupName: ${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.projectCoreRgSuffix}}
        #     location: ${{parameters.deploymentLocation}}
        #     templateFilePath: '$(Pipeline.Workspace)/s/src/arm/core.json'
        #     armParameterOverrideString: $(overrideParameters)
        #     processOutputs: false
        #     tags: $(Tags)