parameters:
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: environmentName
  type: string
- name: applicationName
  type: string
  default: gateway
- name: deploymentLocation
  type: string
  default: 'westeurope'
- name: projectId
  type: string
  default: 's141'
- name: environmentId
  type: string
- name: projectCoreRgSuffix
  type: string
  default: projectcore

jobs:
- deployment: deploy
  displayName: deploy core vnet - ${{parameters.environmentName}}
  environment: ${{parameters.environmentName}}
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: platform-${{parameters.environmentName}}
  - name: overrideParameters
    value: '
    -applicationName "${{parameters.applicationName}}"
    -environmentName "${{parameters.environmentName}}"
    '
  - name: resourceGroupName
    value: "${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.projectCoreRgSuffix}}"
  - name: resourceGroupGateway
    value: "${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.environmentName}}gateway"
  - name: subscriptionId
    value: "${{parameters.subscriptionId}}"
  - name: applicationName
    value: "${{lower(parameters.applicationName)}}-${{lower(parameters.environmentName)}}-ag"
  - name: subnet
    value: "${{parameters.applicationName}}"
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureCLI@2
          name: startGateWay
          displayName: Stop GateWay & remove old subnet
          inputs:
            azureSubscription: "${{parameters.serviceConnection}}"
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              az network application-gateway stop --subscription $env:SUBSCRIPTIONID --resource-group $env:RESOURCEGROUPGATEWAY --name $env:APPLICATIONNAME
              az network vnet subnet delete --resource-group $env:RESOURCEGROUPNAME --name gateway-new
              az network vnet subnet delete --resource-group $env:RESOURCEGROUPNAME --name $env:SUBNET
        - checkout: self
        - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            subscriptionId: ${{parameters.subscriptionId}}
            resourceGroupName: $(resourceGroupName)
            location: ${{parameters.deploymentLocation}}
            templateFilePath: '$(Pipeline.Workspace)/s/src/arm/core.json'
            armParameterOverrideString: $(overrideParameters)
            processOutputs: false
            tags: $(Tags)