parameters:
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: environmentName
  type: string
- name: applicationName
  type: string
  default: gateway
- name: deploymentLocation
  type: string
  default: 'westeurope'
- name: projectId
  type: string
  default: 's141'
- name: environmentId
  type: string
- name: projectCoreRgSuffix
  type: string
  default: projectcore

jobs:
- deployment: deploy
  displayName: deploy core vnet - ${{parameters.environmentName}}
  environment: ${{parameters.environmentName}}
  pool:
    vmImage: windows-latest
  variables:
  - group: platform-${{parameters.environmentName}}
  - name: overrideParameters
    value: '
    -applicationName "${{parameters.applicationName}}"
    -environmentName "${{parameters.environmentName}}"
    -serviceSubnetPrefix "$(gatewaySubnetPrefix)"
    '
  - name:  serverName
    value: "${{parameters.projectId}}${{parameters.environmentId}}-signin-shd-sql.database.windows.net"
  - name:  databaseName
    value: "${{parameters.projectId}}${{parameters.environmentId}}-signin-organisations-db"
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: AzurePowerShell@5
          name: redirectUrls
          displayName: 'SQL Server Redirect urls list'
          inputs:
            azureSubscription: "${{parameters.ServiceConnection}}"
            ScriptType: 'InlineScript'
            azurePowerShellVersion: 'LatestVersion'
            inline: |
              $sqlServerFQDN = $env:SERVERNAME

              $databaseName = $env:DATABASENAME

              $user = $env:AUDITSQLLOGIN
              $pass = $env:AUDITSQLPASSWORD

              $userQuery = "
                declare @results varchar(max)

                select @results = coalesce(@results + ',', '') +  [redirectUrl]
                from [dbo].[serviceRedirectUris]
                order by [redirectUrl]

                select @results as results
              "

              $results = Invoke-Sqlcmd -ServerInstance $sqlServerFQDN -Database $databaseName -Username $user -Password $pass  -query $userQuery  -Verbose 
              $resultsS = '(' + $results['results'] + ')'
              Write-Host "##vso[task.setvariable variable=redirectUrls;isoutput=ture]$resultsS"

              Write-Output $resultsS
          env:
            AUDITSQLLOGIN: $(auditSqlLogin)
            AUDITSQLPASSWORD: $(auditSqlPassword)
        # - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
        #   parameters:
        #     serviceConnection: ${{parameters.serviceConnection}}
        #     subscriptionId: ${{parameters.subscriptionId}}
        #     resourceGroupName: ${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.projectCoreRgSuffix}}
        #     location: ${{parameters.deploymentLocation}}
        #     templateFilePath: '$(Pipeline.Workspace)/s/src/arm/core.json'
        #     armParameterOverrideString: $(overrideParameters)
        #     processOutputs: false
        #     tags: $(Tags)