parameters:
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: environmentName
  type: string
- name: applicationName
  type: string
  default: gateway
- name: deploymentLocation
  type: string
  default: 'westeurope'
- name: projectId
  type: string
  default: 's141'
- name: environmentId
  type: string


jobs:
  
- deployment: deploy
  displayName: deploy test apis - ${{parameters.environmentName}}
  environment: ${{parameters.environmentName}}
  pool:
    vmImage: ubuntu-latest
  variables:
    overrideParameters: '
    -applicationName "${{parameters.applicationName}}"
    -environmentName "${{parameters.environmentName}}"
    '
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            subscriptionId: ${{parameters.subscriptionId}}
            resourceGroupName: ${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.environmentName}}gateway
            location: ${{parameters.deploymentLocation}}
            templateFilePath: '$(Pipeline.Workspace)/s/login.dfe.gateway/src/arm/service-plans.json'
            armParameterOverrideString: $(overrideParameters)
            processOutputs: false

        - template: /Application/dotnet/steps/deploy-appservice.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            resourceGroupName: ${{parameters.projectId}}${{parameters.environmentId}}-${{parameters.environmentName}}gateway
            location: ${{parameters.deploymentLocation}}
            templateFilePath: '$(Pipeline.Workspace)/s/login.dfe.gateway/src/arm/service-plans.json'
            armParameterOverrideString: $(overrideParameters)
            processOutputs: false